baseURL = "https://marcelkliemannel.com"
languageCode = "en-us"
title = "Marcel Kliemannel"
theme = "basic"
enableGitInfo = true

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[markup]
  [markup.highlight]
    lineNos = true
    style = "borland"
    tabWidth = 2
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = false

[params]
  metaLanguage = "en-us"
  metaAuthor = "Marcel Kliemannel"
  metaDescription = "Personal website containing articles and a bookmarks collection mainly about software development and an overview over my projects."
  aboutTheAuthorName = "Marcel Kliemannel"
  # Text is also in the _index.md
  aboutTheAuthorDescription = "Software Engineer, JVM Enthusiast and technical writer with a focus on architecture, backend, automation, DevOps, monitoring, performance, and security."
  gitHubUser = "marcelkliemannel"
  stackOverflow = "https://stackoverflow.com/users/story/7059880"
  twitterUser = "7ur1n9"