baseURL = "https://marcelkliemannel.com"
languageCode = "en-us"
title = "Marcel Kliemannel"
theme = "basic"
enableGitInfo = true
paginate = 8

[related]
  includeNewer = true
  threshold = 50
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[markup]
  [markup.highlight]
    lineNos = true
    style = "borland"
    tabWidth = 2
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = false

[params]
  metaLanguage = "en-us"
  metaAuthor = "Marcel Kliemannel"
  metaDescription = "Personal website containing articles and a bookmarks collection mainly about software development and an overview over my projects."
  aboutTheAuthorName = "Marcel Kliemannel"
  # Text is also in the _index.md
  aboutTheAuthorDescription = "Software Engineer, JVM Enthusiast and technical writer with a focus on architecture, backend, security, automation, DevOps, monitoring, and performance."
  gitHubUser = "marcelkliemannel"
  twitterUser = "7ur1n9"