baseURL = "https://marcelkliemannel.com"
locale = "en-US"
title = "Marcel Kliemannel"
theme = "basic"
enableGitInfo = true

[pagination]
  pagerSize = 8

[related]
  includeNewer = true
  threshold = 50
  toLower = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    style = "borland"
    tabWidth = 2
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = false

[params]
  metaLanguage = "en-US"
  metaAuthor = "Marcel Kliemannel"
  metaDescription = "Personal website with articles, bookmarks, and open-source projects, mainly about software development."
  aboutTheAuthorName = "Marcel Kliemannel"
  # Text is also in the _index.md
  aboutTheAuthorDescription = "Software engineer, JVM enthusiast, and technical writer focused on architecture, backend development, security, automation, DevOps, monitoring, and performance."
  gitHubUser = "marcelkliemannel"
